language: java

before_install:
  - cp src/main/properties/log4j.properties src/test/resources/log4j.properties
  - mkdir -p "gerbil_data"
  - curl --retry 4 -L -o "gerbil_data/gerbil_data.zip" "https://github.com/AKSW/gerbil/releases/download/v1.2.4/gerbil_data.zip"
  - unzip "gerbil_data/gerbil_data.zip"